### ISSUE TITLE
Unifying `Vec A (2 ^ k + 0)` with `Vec A (2 ^ k)`

### ISSUE THREAD

**Issue by umazalakain** [scott-fleischman/agda-binary-vector#1]
Hi. I answered your question on #Agda, but immediately after that you left. I use Matrix to connect to Freenode, and I suspect the Matrix-to-IRC bridge didn't hand you my message.

Anyway, someone answered the same question just a few days ago. Have a look at `Relation.Binary.PropositionalEquality.subst` in the standard library. It shows that, if a predicate `P` holds for some `x` and there is a proof that `x == y`, then `P y`.

**Comment by scott-fleischman** [comment]
Thanks--that helps a lot! Sorry I didn't see your message before I left.
